[package]
name = "wiff-config"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
directories.workspace = true
serde = { workspace = true }
thiserror.workspace = true
toml.workspace = true
wiff-core.workspace = true
wiff-diff.workspace = true
wiff-forge.workspace = true
wiff-tui.workspace = true

[dev-dependencies]
wince.workspace = true
