[package]
name = "wiff-forge"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
octocrab.workspace = true
serde = { workspace = true }
serde_json.workspace = true
similar.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
url.workspace = true
wiff-core.workspace = true
wiff-diff.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
time = { workspace = true, features = ["macros"] }
wince.workspace = true
wiremock.workspace = true
