name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup show
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - run: make test

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --all -- --check
